COMPONENT_ADD_INCLUDEDIRS := include
# COMPONENT_PRIV_INCLUDEDIRS := private_include
COMPONENT_SUBMODULES += cardsim
COMPONENT_ADD_INCLUDEDIRS := include
COMPONENT_SRCDIRS :=  cardsim .
COMPONENT_PRIV_INCLUDEDIRS := include