# COMPONENT_ADD_INCLUDEDIRS := include
# COMPONENT_PRIV_INCLUDEDIRS := private_include
COMPONENT_SUBMODULES += gwp5043
COMPONENT_ADD_INCLUDEDIRS := include
COMPONENT_SRCDIRS :=  gwp5043 .
COMPONENT_PRIV_INCLUDEDIRS := include