COMPONENT_ADD_INCLUDEDIRS := include
# COMPONENT_PRIV_INCLUDEDIRS := private_include
COMPONENT_SUBMODULES += touchpad_api
COMPONENT_ADD_INCLUDEDIRS := include
COMPONENT_SRCDIRS :=  touchpad_api .
COMPONENT_PRIV_INCLUDEDIRS := include